spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: test_user
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/shoes
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 200 #지연 로딩 성능 최적화
#        use_sql_comments: true #jpql 쿼리문 보이게

  messages:
    basename: messages, errors

#  data:
#    web:
#      pageable:
#        default-page-size: 50
#        max-page-size: 100

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
#    org.apache.coyote.http11: debug #http메세지를 서버에서 로그로 남김

server:
  servlet:
    session:
      tracking-modes: cookie

file.dir: C:/Users/uk/mydirectory/imageFolder/