spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shoes
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
#        default_batch_fetch_size: 100 #in 파라미터 개수

  messages:
    basename: messages, errors

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
#    org.apache.coyote.http11: debug #http메세지를 서버에서 로그로 남김

server:
  servlet:
    session:
      tracking-modes: cookie

file.dir: C:/Users/uk/mydirectory/myprojects/imgsFolder/secondshoes/src/main/resources/images/